image: logiquedev/maven-sshpass:v1.0.0

stages:
  - build
  - test
  - package
##  - deploy

before_script:
  - 'echo "Propriedades passadas para o maven: $MAVEN_OPTS"'

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile -DskipTests

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
    paths:
      - target/jacoco.exec
      - target/surefire-reports/*
  allow_failure: true

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests -DjarFileName=starter-api
  only:
    - master
    - develop
  artifacts:
    paths:
      - target/*.jar
      - target/*.war

package_tag:
  stage: package
  script:
    - mvn versions:set -DbuildVersion=$CI_COMMIT_TAG
    - mvn $MAVEN_CLI_OPTS package -DskipTests -DjarFileName=starter-api-$CI_COMMIT_TAG
  only:
    - tags
  artifacts:
    paths:
      - target/*.jar
      - target/*.war

#deploy_homol:
#  stage: deploy
#  script:
#    - sshpass -V
#    - export SSHPASS=$HOMOLOGATION_SSH_PASSWORD
#    - sshpass -e ssh -p 8823 -o stricthostkeychecking=no $HOMOLOGATION_SSH_USER@$HOMOLOGATION_SSH_HOST 'sudo service starter-api stop'
#    - sshpass -e scp -P 8823 -o stricthostkeychecking=no -v ./target/starter-api.jar $HOMOLOGATION_SSH_USER@$HOMOLOGATION_SSH_HOST:/home/logique/starter
#    - sshpass -e ssh -p 8823 -o stricthostkeychecking=no $HOMOLOGATION_SSH_USER@$HOMOLOGATION_SSH_HOST 'chmod 777 /home/logique/starteer/starter-api.jar'
#    - sshpass -e ssh -p 8823 -o stricthostkeychecking=no $HOMOLOGATION_SSH_USER@$HOMOLOGATION_SSH_HOST 'sudo service starter-api start'
#  only:
#    - master
